### ISSUE TITLE
Assert file on macOS due to case mismatch for files path

### ISSUE THREAD

**Issue by franko** [septag/dmon#14]
I have got an assertion fail in the function `dmon__fsevent_callback` for the macOS implementation. It happens in the line there:

```c
        // strip the root dir
        DMON_ASSERT(strstr(abs_filepath, watch->rootdir) == abs_filepath);
        dmon__strcpy(ev.filepath, sizeof(ev.filepath), abs_filepath + strlen(watch->rootdir));
```

The reason is that although `abs_filepath` actually begins with `watch->rootdir` but they have a different case. I think if the directory for which an event is reported has some uppercase part it is reported with lowercase anyway.

I did some research and on macOS the filesystems can be case sensitive or not and it depends on the volume. In practice I think that most commonly volumes are case insensitive. In theory we should compare with a case sensitivity adapted on the volume but I am perplexed.

**Comment by septag** [comment]
hm.. weird. because I visited this recently , as you can see here, https://github.com/septag/dmon/commit/7568e8a50e1471831563f750284a7636b0af9064, I'm converting the rootdir to lower case as well as `abs_filepath` , so there should be no case differences.

And yeah, Mac can have both filesystems, I'm going to improve that in the next commit, so what they report to the user is not case modified.

**Comment by septag** [comment]
I also tested with different cases, the assert fail didn't happen. could you come up with your specific case ?

**Comment by septag** [comment]
Also, in the last commit 861001f7f40974ebccb7107732ee78b7e1a65a95, it is now reporting the correct path cases

**Comment by franko** [comment]
Ok, thank you, it is just that I was using dmon.h from the branch inotify-bulk-changes so I didn't see the modifications you did recently.

I will use the version with the changes you made for macOS. I will close the issue if the tests are fine.

**Comment by franko** [comment]
I confirm with the changes in the master branch now everything works on macOS.

I tested only on one volume with a case insensitive file-system.
