### ISSUE TITLE
Replace SX_ stuff

### ISSUE THREAD

**Issue by jesta88** [septag/dmon#2]
There are some remnants of sx_ functions and defines. They are very easy to replace (strlen, min, platform defines) and would make the library independent.

**Comment by septag** [comment]
oh! thank you. 

I actually never noticed it cuz I never got any errors from compiler since it wasn't used in windows impl, so I guess we can ditch the whole thing.

**Comment by septag** [comment]
fixed 30474964b1b5937f80666809615e22eb4dcbc510
