### ISSUE TITLE
MacOS 12 Apple M1 issue

### ISSUE THREAD

**Issue by uliss** [septag/dmon#25]
File update (``echo test >> test_file``) and move events are recorgnized as **create** event.

Only **create** and **remove** events are recognized stable, sometimes **update** event is receiveed.

``./dmon_test .``

``rm 1 && touch 1 && sleep 1 && echo test > 1``

**Comment by uliss** [comment]
seems that events are grouped, so if i change

``} else if (ev->event_flags & kFSEventStreamEventFlagItemModified) {``

to
``}
   if (ev->event_flags & kFSEventStreamEventFlagItemModified) {``
   
   everything works fine

**Comment by septag** [comment]
sorry for a "little bit of delay" in response 
I fixed it according to your suggestion. Thanks!

**Comment by adeopura4** [comment]
Hi - wanted to check if this is working for you? When I change the contents of a file (say a text file) on Apple M1 MacOS (14.1.1) , I see that the event is recognized as a create event. 

I do have the latest version of your code as of Dec 1, 2023 and it includes the changes that were proposed in this issue.
