### ISSUE TITLE
Unwatching dirs in the same order that  they were supplied  raise an assert.

### ISSUE THREAD

**Issue by fmor** [septag/dmon#26]
Hi,

First, thanks for sharing your work. Maybe i missed something in the documentation but  dmon raise an assert when unwatching dirs in the same order that they were supplied, maybe will happen if unwatching randomly too. Below is a small test programm  to illustrate this behaviour.  

```C
#define DMON_IMPL
#include "dmon.h"

#include <assert.h>

void cb( dmon_watch_id id,  dmon_action action, const char* dir, const char* filename, const char* old_filename, void* opaque )
{
}

void main()
{
    static const char* dirs[] = { "/bin/", "/home", "/tmp", "/usr", "/usr/share", "/var" };
    dmon_watch_id ids[6];
    dmon_init();

    for( int i = 0; i < 6; ++i )
    {
        ids[i] = dmon_watch( dirs[i] , cb, 0, NULL );
        assert( ids[i].id != 0 );
    }

   for( int i = 0; i < 6 ; ++i )
       dmon_unwatch( ids[i] );
   dmon_deinit();
}

```

**Comment by krumelmonster** [comment]
It seems to me that [dmon.h:1202](https://github.com/septag/dmon/blob/master/dmon.h#L1202) will free space in the _dmon.watches array by swapping the removed element with the last element. So as soon as you unwatch `ids[0]`, `ids[5]` becomes invalid as 5 is stored in 0 now. It seems a lot like a bug to me. As a workaround, I guess you could remove all three of those ([windows](https://github.com/septag/dmon/blob/master/dmon.h#L672C1-L675C25), [linux](https://github.com/septag/dmon/blob/master/dmon.h#L1201C1-L1204C25),[mac](https://github.com/septag/dmon/blob/master/dmon.h#L1610C1-L1613C25)) from dmon.h and you'd be fine as long as you don't create more than a total of `DMON_MAX_WATCHES` throughout the lifetime of your program.

**Comment by krumelmonster** [comment]
Thinking about how to actually solve this: Is there a good reason to not just heap-allocate each dmon__watch_state individually and include a pointer to it in dmon__watch_state?

**Comment by septag** [comment]
sorry for a "little bit of delay" in response :D. I totally missed this thread.
Anyways, I took a new approach using freelists, and it should be fixed now. Although haven't tested it that much, if there is any regression bugs, please feel free to re-open this.
