### ISSUE TITLE
_DMON_WINAPI_STR does not set any memory

### ISSUE THREAD

**Issue by jesta88** [septag/dmon#3]
On Windows, `_DMON_WINAPI_STR` gives me gibberish. I think the memory is simply not set. Replacing it with the following works:

`#   define _DMON_WINAPI_STR(name, size) wchar_t _##name[size]; mbstowcs(_##name, name, size)`

**Comment by septag** [comment]
instead of `MultiByteToWideChar` ?

**Comment by jesta88** [comment]
`MultiByteToWideChar` should work too, I was just more familiar with its little cousin `mbstowcs`.

But it surely can't work in the actual state, since the line `MultiByteToWideChar(CP_UTF8, 0, name, -1, 0, 0)` doesn't do anything. You need to specify the destination buffer and it size for the last 2 arguments (`_##name, size`).

**Comment by septag** [comment]
whoops. you are right. fixed in 488ba5213221e12f94c8f9dd278c510ae5c92895 
thanks
