### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by waypar** [septag/dmon#6]
Hi,
Thanks for the useful library, I'm using it on linux, but i've come up to an issue where dmon will use a high amount of CPU on Ubuntu 18.04.

I've looked at the code, it seems to be an issue with the use of select().
select() will set the timeout to the amount of time not slept on return, which is going to be 0 if no filesystem events occurred.  The timeout doesn't ever get reinitialised, so subsequent calls to select return immediately and we end up in a high speed loop situation.

I observed different behaviour in debug mode, select returned -1 and errno was 22 invald argument, I don't know if this is something specific to my program.

There is another thing I noticed that could be done more efficiently.
At the moment each watch is checked individually in a loop. It should be possible to populate rfds with all the current watches and use a single select to wait for changes rather than 1 each. This will cause delays of up to num_watches * 0.1s  for responding to changes.

If you agree with these issues I'm happy to look at doing PR's.
Thanks again :)

**Comment by septag** [comment]
Hi,
Yeah, my main testing platform is windows, so It's probably missing polish in other platforms.
I'll be glad if you could submit a PR on this.
Thanks

**Comment by septag** [comment]
Thanks for the PR
btw, are you planning to submit a PR for batching select calls as well ?
as a side note, similar thing is implemented in the windows backend (`WaitForMultipleObjects`),

**Comment by waypar** [comment]
I have a branch on my fork for it, but I haven’t really tested it yet.

**Comment by septag** [comment]
all things here resolved with #8
