### ISSUE TITLE
File path inconsistency

### ISSUE THREAD

**Issue by waypar** [septag/dmon#9]
Hey,
I've just noticed an inconsistency between linux and windows, windows seems to just have the filename in the callback filepath, where linux has the full file path.
What is the desired behaviour?
Thanks,
Wayne

**Comment by septag** [comment]
oh no!
expected behavior is to give you relative paths, that's why we have `rootdir` argument in the callback.
check out the latest commit 48234fc2a42e699b7f210df994ecbdb95bffb846, I fixed it for linux. probably more testing needs to be done.
